[pytest]
# only files with prefix `pytest_` are recognized as pytest scripts
python_files = pytest_*.py

addopts =
  -s
  --embedded-services esp,idf
  --tb short
  --strict-markers
  --skip-check-coredump y

# register custom markers used by pytest_*.py to silence PytestUnknownMarkWarning
markers =
  esp32s3: target chip esp32s3
  esp32s31: target chip esp32s31
  esp32p4: target chip esp32p4

filterwarnings =
  ignore::_pytest.warning_types.PytestExperimentalApiWarning

# log related
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# junit related
junit_family = xunit1
junit_logging = stdout
junit_log_passing_tests = False
